project:
  type: website
  output-dir: ../_site

execute:
  dir: project
  
website:
  title: "Luften i snicken"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Daily"
        href: analysis/daily.qmd

format:
  html:
    theme: cosmo
    toc: true
